"""fittbot_models_sync

Revision ID: 67f22f0eb185
Revises: ebe22aa97eed
Create Date: 2025-12-06 20:02:12.612499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67f22f0eb185'
down_revision: Union[str, Sequence[str], None] = 'ebe22aa97eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['email'])
    op.alter_column('default_workout_templates', 'gender',
               existing_type=mysql.ENUM('male', 'female'),
               nullable=True)
    op.alter_column('default_workout_templates', 'goals',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('default_workout_templates', 'expertise_level',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('default_workout_templates', 'workout_json',
               existing_type=mysql.JSON(),
               nullable=True)
    op.create_index(op.f('ix_default_workout_templates_id'), 'default_workout_templates', ['id'], unique=False)
    op.create_index(op.f('ix_fittbot_diet_template_id'), 'fittbot_diet_template', ['id'], unique=False)
    op.alter_column('fittbot_food', 'is_manual',
               existing_type=mysql.TINYINT(),
               nullable=True)
    op.create_index(op.f('ix_fittbot_food_id'), 'fittbot_food', ['id'], unique=False)
    op.drop_index(op.f('idx_gender'), table_name='fittbot_muscle_group')
    op.drop_index(op.f('idx_muscle_group'), table_name='fittbot_muscle_group')
    op.drop_index(op.f('idx_client_id'), table_name='fittbot_ratings')
    op.create_index(op.f('ix_fittbot_ratings_client_id'), 'fittbot_ratings', ['client_id'], unique=False)
    op.create_index(op.f('ix_fittbot_ratings_id'), 'fittbot_ratings', ['id'], unique=False)
    op.drop_index(op.f('uq_gym_details_gym_id'), table_name='gym_details')
    op.create_index(op.f('ix_gym_details_gym_id'), 'gym_details', ['gym_id'], unique=True)
    op.create_index(op.f('ix_gym_details_id'), 'gym_details', ['id'], unique=False)
    op.add_column('gym_import_data', sa.Column('joined_at', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_gym_manual_data_gym_id'), table_name='gym_manual_data')
    op.create_index(op.f('ix_gym_manual_data_gym_id'), 'gym_manual_data', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_manual_data_id'), 'gym_manual_data', ['id'], unique=False)
    op.create_foreign_key(None, 'gym_studios_pic', 'gyms', ['gym_id'], ['gym_id'], ondelete='CASCADE')
    op.alter_column('gym_verification_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gym_verification_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_gvd_gym_id'), table_name='gym_verification_documents')
    op.create_index(op.f('ix_gym_verification_documents_gym_id'), 'gym_verification_documents', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_verification_documents_id'), 'gym_verification_documents', ['id'], unique=False)
    op.drop_constraint(op.f('fk_gvd_gym'), 'gym_verification_documents', type_='foreignkey')
    op.create_foreign_key(None, 'gym_verification_documents', 'gyms', ['gym_id'], ['gym_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_home_posters_id'), 'home_posters', ['id'], unique=False)
    op.create_index(op.f('ix_home_workout_id'), 'home_workout', ['id'], unique=False)
    op.alter_column('indian_food_master', 'is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_non_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_eggetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_jain',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_paleo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_ketogenic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_early_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_mid_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_lunch',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_evening_snack',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_post_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_dinner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_bedtime',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_diabetic_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_high_protein',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_low_calorie',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_weight_loss_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_muscle_gain_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_heart_healthy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_lactose_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_liquid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_seasonal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('indian_food_master', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'popularity_score',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_indian_food_master_is_eggetarian'), 'indian_food_master', ['is_eggetarian'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_gluten_free'), 'indian_food_master', ['is_gluten_free'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_heart_healthy'), 'indian_food_master', ['is_heart_healthy'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_jain'), 'indian_food_master', ['is_jain'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_ketogenic'), 'indian_food_master', ['is_ketogenic'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_lactose_free'), 'indian_food_master', ['is_lactose_free'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_muscle_gain_friendly'), 'indian_food_master', ['is_muscle_gain_friendly'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_paleo'), 'indian_food_master', ['is_paleo'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_vegan'), 'indian_food_master', ['is_vegan'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_weight_loss_friendly'), 'indian_food_master', ['is_weight_loss_friendly'], unique=False)
    op.alter_column('live_count', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('owner_id'), table_name='referral_gym_code')
    op.drop_index(op.f('referral_code'), table_name='referral_gym_code')
    op.drop_index(op.f('ix_referral_gym_code_owner_id'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_owner_id'), 'referral_gym_code', ['owner_id'], unique=True)
    op.drop_index(op.f('ix_referral_gym_code_referral_code'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_referral_code'), 'referral_gym_code', ['referral_code'], unique=True)
    op.alter_column('reminders', 'queued',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.create_index(op.f('ix_reminders_gym_id'), 'reminders', ['gym_id'], unique=False)
    op.alter_column('rewards_badges', 'level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('voice_preference', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('voice_preference', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_preference', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('voice_preference', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rewards_badges', 'level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_reminders_gym_id'), table_name='reminders')
    op.alter_column('reminders', 'queued',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.drop_index(op.f('ix_referral_gym_code_referral_code'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_referral_code'), 'referral_gym_code', ['referral_code'], unique=False)
    op.drop_index(op.f('ix_referral_gym_code_owner_id'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_owner_id'), 'referral_gym_code', ['owner_id'], unique=False)
    op.create_index(op.f('referral_code'), 'referral_gym_code', ['referral_code'], unique=True)
    op.create_index(op.f('owner_id'), 'referral_gym_code', ['owner_id'], unique=True)
    op.alter_column('live_count', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_indian_food_master_is_weight_loss_friendly'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_vegan'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_paleo'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_muscle_gain_friendly'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_lactose_free'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_ketogenic'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_jain'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_heart_healthy'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_gluten_free'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_eggetarian'), table_name='indian_food_master')
    op.alter_column('indian_food_master', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'popularity_score',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('indian_food_master', 'is_seasonal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_liquid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_lactose_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_heart_healthy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_muscle_gain_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_weight_loss_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_low_calorie',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_high_protein',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_diabetic_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_bedtime',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_dinner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_post_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_evening_snack',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_lunch',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_mid_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_early_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_ketogenic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_paleo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_jain',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_eggetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_non_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_home_workout_id'), table_name='home_workout')
    op.drop_index(op.f('ix_home_posters_id'), table_name='home_posters')
    op.drop_constraint(None, 'gym_verification_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gvd_gym'), 'gym_verification_documents', 'gyms', ['gym_id'], ['gym_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_gym_verification_documents_id'), table_name='gym_verification_documents')
    op.drop_index(op.f('ix_gym_verification_documents_gym_id'), table_name='gym_verification_documents')
    op.create_index(op.f('idx_gvd_gym_id'), 'gym_verification_documents', ['gym_id'], unique=False)
    op.alter_column('gym_verification_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('gym_verification_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'gym_studios_pic', type_='foreignkey')
    op.drop_index(op.f('ix_gym_manual_data_id'), table_name='gym_manual_data')
    op.drop_index(op.f('ix_gym_manual_data_gym_id'), table_name='gym_manual_data')
    op.create_index(op.f('idx_gym_manual_data_gym_id'), 'gym_manual_data', ['gym_id'], unique=False)
    op.drop_column('gym_import_data', 'joined_at')
    op.drop_index(op.f('ix_gym_details_id'), table_name='gym_details')
    op.drop_index(op.f('ix_gym_details_gym_id'), table_name='gym_details')
    op.create_index(op.f('uq_gym_details_gym_id'), 'gym_details', ['gym_id'], unique=True)
    op.drop_index(op.f('ix_fittbot_ratings_id'), table_name='fittbot_ratings')
    op.drop_index(op.f('ix_fittbot_ratings_client_id'), table_name='fittbot_ratings')
    op.create_index(op.f('idx_client_id'), 'fittbot_ratings', ['client_id'], unique=False)
    op.create_index(op.f('idx_muscle_group'), 'fittbot_muscle_group', ['muscle_group'], unique=False)
    op.create_index(op.f('idx_gender'), 'fittbot_muscle_group', ['gender'], unique=False)
    op.drop_index(op.f('ix_fittbot_food_id'), table_name='fittbot_food')
    op.alter_column('fittbot_food', 'is_manual',
               existing_type=mysql.TINYINT(),
               nullable=False)
    op.drop_index(op.f('ix_fittbot_diet_template_id'), table_name='fittbot_diet_template')
    op.drop_index(op.f('ix_default_workout_templates_id'), table_name='default_workout_templates')
    op.alter_column('default_workout_templates', 'workout_json',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('default_workout_templates', 'expertise_level',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('default_workout_templates', 'goals',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('default_workout_templates', 'gender',
               existing_type=mysql.ENUM('male', 'female'),
               nullable=False)
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
