"""fittbot_models_sync

Revision ID: ebe22aa97eed
Revises: 
Create Date: 2025-12-06 19:57:44.157527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebe22aa97eed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fittbot_associates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('gym_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fittbot_associates_id'), 'fittbot_associates', ['id'], unique=False)
    op.create_index(op.f('ix_fittbot_associates_mobile_number'), 'fittbot_associates', ['mobile_number'], unique=True)
    op.create_table('gym_onboarding_pics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('machinery_1', sa.String(length=255), nullable=True),
    sa.Column('machinery_2', sa.String(length=255), nullable=True),
    sa.Column('treadmill_area', sa.String(length=255), nullable=True),
    sa.Column('cardio_area', sa.String(length=255), nullable=True),
    sa.Column('dumbell_area', sa.String(length=255), nullable=True),
    sa.Column('reception_area', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_onboarding_pics_gym_id'), 'gym_onboarding_pics', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_onboarding_pics_id'), 'gym_onboarding_pics', ['id'], unique=False)
    op.create_table('gym_join_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('alternate_mobile_number', sa.String(length=15), nullable=True),
    sa.Column('dp', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.gym_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_join_requests_client_id'), 'gym_join_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_gym_join_requests_gym_id'), 'gym_join_requests', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_join_requests_id'), 'gym_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_gym_join_requests_status'), 'gym_join_requests', ['status'], unique=False)
    op.create_table('reward_interest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('interested', sa.Boolean(), nullable=True),
    sa.Column('next_reminder', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_reward_interest_id'), 'reward_interest', ['id'], unique=False)
    op.drop_index(op.f('idx_client_date'), table_name='actual_diet')
    op.create_index('ix_attendance_client_date', 'attendance', ['client_id', 'date'], unique=False)
    op.create_index('ix_attendance_gym_date', 'attendance', ['gym_id', 'date'], unique=False)
    op.drop_index(op.f('id_UNIQUE'), table_name='avatar')
    op.alter_column('characters_combination', 'characters_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('characters_combination', 'gender',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.create_index(op.f('ix_characters_combination_id'), 'characters_combination', ['id'], unique=False)
    op.alter_column('client_birthdays', 'expo_token',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index(op.f('idx_client_characters_character_id'), table_name='client_characters')
    op.drop_index(op.f('idx_client_characters_client_id'), table_name='client_characters')
    op.drop_index(op.f('uq_client_character_pair'), table_name='client_characters')
    op.create_index(op.f('ix_client_characters_character_id'), 'client_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_client_characters_client_id'), 'client_characters', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_characters_id'), 'client_characters', ['id'], unique=False)
    op.create_unique_constraint(None, 'clients', ['email'])
    op.alter_column('default_workout_templates', 'gender',
               existing_type=mysql.ENUM('male', 'female'),
               nullable=True)
    op.alter_column('default_workout_templates', 'goals',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('default_workout_templates', 'expertise_level',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('default_workout_templates', 'workout_json',
               existing_type=mysql.JSON(),
               nullable=True)
    op.create_index(op.f('ix_default_workout_templates_id'), 'default_workout_templates', ['id'], unique=False)
    op.create_index(op.f('ix_fittbot_diet_template_id'), 'fittbot_diet_template', ['id'], unique=False)
    op.alter_column('fittbot_food', 'is_manual',
               existing_type=mysql.TINYINT(),
               nullable=True)
    op.create_index(op.f('ix_fittbot_food_id'), 'fittbot_food', ['id'], unique=False)
    op.drop_index(op.f('idx_gender'), table_name='fittbot_muscle_group')
    op.drop_index(op.f('idx_muscle_group'), table_name='fittbot_muscle_group')
    op.drop_index(op.f('idx_client_id'), table_name='fittbot_ratings')
    op.create_index(op.f('ix_fittbot_ratings_client_id'), 'fittbot_ratings', ['client_id'], unique=False)
    op.create_index(op.f('ix_fittbot_ratings_id'), 'fittbot_ratings', ['id'], unique=False)
    op.drop_index(op.f('uq_gym_details_gym_id'), table_name='gym_details')
    op.create_index(op.f('ix_gym_details_gym_id'), 'gym_details', ['gym_id'], unique=True)
    op.create_index(op.f('ix_gym_details_id'), 'gym_details', ['id'], unique=False)
    op.add_column('gym_import_data', sa.Column('joined_at', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_gym_manual_data_gym_id'), table_name='gym_manual_data')
    op.create_index(op.f('ix_gym_manual_data_gym_id'), 'gym_manual_data', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_manual_data_id'), 'gym_manual_data', ['id'], unique=False)
    op.create_foreign_key(None, 'gym_studios_pic', 'gyms', ['gym_id'], ['gym_id'], ondelete='CASCADE')
    op.alter_column('gym_verification_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gym_verification_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_gvd_gym_id'), table_name='gym_verification_documents')
    op.create_index(op.f('ix_gym_verification_documents_gym_id'), 'gym_verification_documents', ['gym_id'], unique=False)
    op.create_index(op.f('ix_gym_verification_documents_id'), 'gym_verification_documents', ['id'], unique=False)
    op.drop_constraint(op.f('fk_gvd_gym'), 'gym_verification_documents', type_='foreignkey')
    op.create_foreign_key(None, 'gym_verification_documents', 'gyms', ['gym_id'], ['gym_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_home_posters_id'), 'home_posters', ['id'], unique=False)
    op.create_index(op.f('ix_home_workout_id'), 'home_workout', ['id'], unique=False)
    op.alter_column('indian_food_master', 'is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_non_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_eggetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_jain',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_paleo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_ketogenic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_early_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_mid_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_lunch',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_evening_snack',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_post_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_dinner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_bedtime',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_diabetic_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_high_protein',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_low_calorie',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_weight_loss_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_muscle_gain_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_heart_healthy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_lactose_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_liquid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_seasonal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('indian_food_master', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'popularity_score',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_indian_food_master_is_eggetarian'), 'indian_food_master', ['is_eggetarian'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_gluten_free'), 'indian_food_master', ['is_gluten_free'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_heart_healthy'), 'indian_food_master', ['is_heart_healthy'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_jain'), 'indian_food_master', ['is_jain'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_ketogenic'), 'indian_food_master', ['is_ketogenic'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_lactose_free'), 'indian_food_master', ['is_lactose_free'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_muscle_gain_friendly'), 'indian_food_master', ['is_muscle_gain_friendly'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_paleo'), 'indian_food_master', ['is_paleo'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_vegan'), 'indian_food_master', ['is_vegan'], unique=False)
    op.create_index(op.f('ix_indian_food_master_is_weight_loss_friendly'), 'indian_food_master', ['is_weight_loss_friendly'], unique=False)
    op.alter_column('live_count', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('owner_id'), table_name='referral_gym_code')
    op.drop_index(op.f('referral_code'), table_name='referral_gym_code')
    op.drop_index(op.f('ix_referral_gym_code_owner_id'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_owner_id'), 'referral_gym_code', ['owner_id'], unique=True)
    op.drop_index(op.f('ix_referral_gym_code_referral_code'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_referral_code'), 'referral_gym_code', ['referral_code'], unique=True)
    op.alter_column('reminders', 'queued',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.create_index(op.f('ix_reminders_gym_id'), 'reminders', ['gym_id'], unique=False)
    op.alter_column('rewards_badges', 'level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('voice_preference', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('voice_preference', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_preference', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('voice_preference', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rewards_badges', 'level',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_reminders_gym_id'), table_name='reminders')
    op.alter_column('reminders', 'queued',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.drop_index(op.f('ix_referral_gym_code_referral_code'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_referral_code'), 'referral_gym_code', ['referral_code'], unique=False)
    op.drop_index(op.f('ix_referral_gym_code_owner_id'), table_name='referral_gym_code')
    op.create_index(op.f('ix_referral_gym_code_owner_id'), 'referral_gym_code', ['owner_id'], unique=False)
    op.create_index(op.f('referral_code'), 'referral_gym_code', ['referral_code'], unique=True)
    op.create_index(op.f('owner_id'), 'referral_gym_code', ['owner_id'], unique=True)
    op.alter_column('live_count', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_indian_food_master_is_weight_loss_friendly'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_vegan'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_paleo'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_muscle_gain_friendly'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_lactose_free'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_ketogenic'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_jain'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_heart_healthy'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_gluten_free'), table_name='indian_food_master')
    op.drop_index(op.f('ix_indian_food_master_is_eggetarian'), table_name='indian_food_master')
    op.alter_column('indian_food_master', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('indian_food_master', 'popularity_score',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('indian_food_master', 'is_seasonal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_liquid',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_lactose_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_heart_healthy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_muscle_gain_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_weight_loss_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_low_calorie',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_high_protein',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_diabetic_friendly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_bedtime',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_dinner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_post_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_workout',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_evening_snack',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_lunch',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_mid_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_pre_breakfast',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'suitable_for_early_morning',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_ketogenic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_paleo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_jain',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_eggetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_non_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('indian_food_master', 'is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_home_workout_id'), table_name='home_workout')
    op.drop_index(op.f('ix_home_posters_id'), table_name='home_posters')
    op.drop_constraint(None, 'gym_verification_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gvd_gym'), 'gym_verification_documents', 'gyms', ['gym_id'], ['gym_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_gym_verification_documents_id'), table_name='gym_verification_documents')
    op.drop_index(op.f('ix_gym_verification_documents_gym_id'), table_name='gym_verification_documents')
    op.create_index(op.f('idx_gvd_gym_id'), 'gym_verification_documents', ['gym_id'], unique=False)
    op.alter_column('gym_verification_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('gym_verification_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'gym_studios_pic', type_='foreignkey')
    op.drop_index(op.f('ix_gym_manual_data_id'), table_name='gym_manual_data')
    op.drop_index(op.f('ix_gym_manual_data_gym_id'), table_name='gym_manual_data')
    op.create_index(op.f('idx_gym_manual_data_gym_id'), 'gym_manual_data', ['gym_id'], unique=False)
    op.drop_column('gym_import_data', 'joined_at')
    op.drop_index(op.f('ix_gym_details_id'), table_name='gym_details')
    op.drop_index(op.f('ix_gym_details_gym_id'), table_name='gym_details')
    op.create_index(op.f('uq_gym_details_gym_id'), 'gym_details', ['gym_id'], unique=True)
    op.drop_index(op.f('ix_fittbot_ratings_id'), table_name='fittbot_ratings')
    op.drop_index(op.f('ix_fittbot_ratings_client_id'), table_name='fittbot_ratings')
    op.create_index(op.f('idx_client_id'), 'fittbot_ratings', ['client_id'], unique=False)
    op.create_index(op.f('idx_muscle_group'), 'fittbot_muscle_group', ['muscle_group'], unique=False)
    op.create_index(op.f('idx_gender'), 'fittbot_muscle_group', ['gender'], unique=False)
    op.drop_index(op.f('ix_fittbot_food_id'), table_name='fittbot_food')
    op.alter_column('fittbot_food', 'is_manual',
               existing_type=mysql.TINYINT(),
               nullable=False)
    op.drop_index(op.f('ix_fittbot_diet_template_id'), table_name='fittbot_diet_template')
    op.drop_index(op.f('ix_default_workout_templates_id'), table_name='default_workout_templates')
    op.alter_column('default_workout_templates', 'workout_json',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('default_workout_templates', 'expertise_level',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('default_workout_templates', 'goals',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('default_workout_templates', 'gender',
               existing_type=mysql.ENUM('male', 'female'),
               nullable=False)
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_client_characters_id'), table_name='client_characters')
    op.drop_index(op.f('ix_client_characters_client_id'), table_name='client_characters')
    op.drop_index(op.f('ix_client_characters_character_id'), table_name='client_characters')
    op.create_index(op.f('uq_client_character_pair'), 'client_characters', ['client_id', 'character_id'], unique=True)
    op.create_index(op.f('idx_client_characters_client_id'), 'client_characters', ['client_id'], unique=False)
    op.create_index(op.f('idx_client_characters_character_id'), 'client_characters', ['character_id'], unique=False)
    op.alter_column('client_birthdays', 'expo_token',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_characters_combination_id'), table_name='characters_combination')
    op.alter_column('characters_combination', 'gender',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('characters_combination', 'characters_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('id_UNIQUE'), 'avatar', ['id'], unique=True)
    op.drop_index('ix_attendance_gym_date', table_name='attendance')
    op.drop_index('ix_attendance_client_date', table_name='attendance')
    op.create_index(op.f('idx_client_date'), 'actual_diet', ['client_id', 'date'], unique=False)
    op.drop_index(op.f('ix_reward_interest_id'), table_name='reward_interest')
    op.drop_table('reward_interest')
    op.drop_index(op.f('ix_gym_join_requests_status'), table_name='gym_join_requests')
    op.drop_index(op.f('ix_gym_join_requests_id'), table_name='gym_join_requests')
    op.drop_index(op.f('ix_gym_join_requests_gym_id'), table_name='gym_join_requests')
    op.drop_index(op.f('ix_gym_join_requests_client_id'), table_name='gym_join_requests')
    op.drop_table('gym_join_requests')
    op.drop_index(op.f('ix_gym_onboarding_pics_id'), table_name='gym_onboarding_pics')
    op.drop_index(op.f('ix_gym_onboarding_pics_gym_id'), table_name='gym_onboarding_pics')
    op.drop_table('gym_onboarding_pics')
    op.drop_index(op.f('ix_fittbot_associates_mobile_number'), table_name='fittbot_associates')
    op.drop_index(op.f('ix_fittbot_associates_id'), table_name='fittbot_associates')
    op.drop_table('fittbot_associates')
    # ### end Alembic commands ###
