"""
Webhook Processing Logs - For Idempotency and Duplicate Prevention
"""

from sqlalchemy import Column, String, DateTime, Text, Integer, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class WebhookProcessingLog(Base):
    """
    Log all webhook processing to prevent duplicates
    This is the KEY to idempotency!
    """
    __tablename__ = "webhook_processing_logs"
    __table_args__ = {"schema": "payments"}
    
    id = Column(String(255), primary_key=True)
    
    # Idempotency fields
    event_id = Column(String(255), unique=True, index=True)  # RevenueCat event ID or custom ID
    event_type = Column(String(50), index=True)  # INITIAL_PURCHASE, RENEWAL, CANCELLATION, etc.
    
    # Processing details
    customer_id = Column(String(255), index=True)
    status = Column(String(20), index=True)  # processing, completed, failed
    
    # Timing
    started_at = Column(DateTime, index=True)
    completed_at = Column(DateTime, nullable=True)
    
    # Data
    raw_event_data = Column(Text)  # JSON of the original event
    result_summary = Column(Text, nullable=True)  # What was created/updated
    error_message = Column(Text, nullable=True)  # If failed, why
    
    # Metadata
    processing_duration_ms = Column(Integer, nullable=True)
    retry_count = Column(Integer, default=0)
    is_recovery_event = Column(Boolean, default=False)  # True if generated by our recovery system
    
    webhook_source=Column(String(50), nullable=True)  # e.g., "Razorpay", "Stripe", etc.
    
    def __repr__(self):
        return f"<WebhookLog {self.event_id}: {self.event_type} - {self.status}>"


# SQL to create the table
CREATE_WEBHOOK_LOGS_TABLE = """
CREATE TABLE payments.webhook_processing_logs (
    id VARCHAR(255) PRIMARY KEY,
    event_id VARCHAR(255) UNIQUE NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    customer_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NULL,
    raw_event_data TEXT,
    result_summary TEXT,
    error_message TEXT,
    processing_duration_ms INT,
    retry_count INT DEFAULT 0,
    is_recovery_event BOOLEAN DEFAULT FALSE,
    
    INDEX idx_event_id (event_id),
    INDEX idx_event_type (event_type),
    INDEX idx_customer_id (customer_id),
    INDEX idx_status (status),
    INDEX idx_started_at (started_at)
);
"""