"""payments_models_sync

Revision ID: 1790aa290296
Revises: 
Create Date: 2025-12-16 12:18:29.842573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1790aa290296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_earnings',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('earning_type', sa.String(length=30), nullable=False),
    sa.Column('gym_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('pass_day_id', sa.String(length=100), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('recognized_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'earning_type', 'pass_day_id', name='uq_pe_src_type_day'),
    schema='payments'
    )
    op.create_index('idx_pe_gym_time', 'platform_earnings', ['gym_id', 'recognized_on'], unique=False, schema='payments')
    op.drop_index(op.f('id_UNIQUE'), table_name='orders', schema='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('id_UNIQUE'), 'orders', ['id'], unique=True, schema='payments')
    op.drop_index('idx_pe_gym_time', table_name='platform_earnings', schema='payments')
    op.drop_table('platform_earnings', schema='payments')
    # ### end Alembic commands ###
