-- Create webhook idempotency tables in payments schema
-- This ensures webhook processing is idempotent and prevents duplicate processing

USE payments;

-- 1. Webhook Processing Logs (Core idempotency table)
CREATE TABLE webhook_processing_logs (
    id VARCHAR(255) PRIMARY KEY,
    event_id VARCHAR(255) UNIQUE NOT NULL COMMENT 'RevenueCat event ID or generated unique ID for idempotency',
    event_type VARCHAR(50) NOT NULL COMMENT 'INITIAL_PURCHASE, RENEWAL, CANCELLATION, EXPIRATION',
    customer_id VARCHAR(255) NOT NULL COMMENT 'Customer who triggered the webhook',
    status VARCHAR(20) NOT NULL DEFAULT 'processing' COMMENT 'processing, completed, failed',
    
    -- Timing fields
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When processing started',
    completed_at TIMESTAMP NULL COMMENT 'When processing finished (NULL if still processing)',
    processing_duration_ms INT NULL COMMENT 'Processing time in milliseconds',
    
    -- Data fields
    raw_event_data TEXT COMMENT 'Complete webhook JSON for debugging',
    result_summary TEXT COMMENT 'Human readable summary of what was processed',
    error_message TEXT COMMENT 'Error details if processing failed',
    
    -- Metadata fields
    retry_count INT DEFAULT 0 COMMENT 'Number of processing retries',
    is_recovery_event BOOLEAN DEFAULT FALSE COMMENT 'TRUE if generated by webhook recovery system',
    webhook_source VARCHAR(50) DEFAULT 'revenuecat' COMMENT 'Source system that sent webhook',
    
    -- Audit fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for performance
    INDEX idx_webhook_logs_event_id (event_id),
    INDEX idx_webhook_logs_event_type (event_type),
    INDEX idx_webhook_logs_customer_id (customer_id),
    INDEX idx_webhook_logs_status (status),
    INDEX idx_webhook_logs_started_at (started_at),
    INDEX idx_webhook_logs_completed_at (completed_at),
    INDEX idx_webhook_logs_is_recovery (is_recovery_event),
    INDEX idx_webhook_logs_customer_event_type (customer_id, event_type),
    INDEX idx_webhook_logs_status_started (status, started_at),
    INDEX idx_webhook_logs_event_type_status (event_type, status)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Tracks all webhook processing attempts for idempotency and debugging';

-- 2. Webhook Recovery Logs (Track recovery actions)
CREATE TABLE webhook_recovery_logs (
    id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255) COMMENT 'Order that was recovered',
    customer_id VARCHAR(255) NOT NULL COMMENT 'Customer whose payment was recovered',
    
    -- Recovery details
    recovery_reason VARCHAR(100) NOT NULL COMMENT 'missed_webhook, payment_failed, billing_error, etc.',
    original_webhook_type VARCHAR(50) COMMENT 'INITIAL_PURCHASE, RENEWAL, etc.',
    recovery_action VARCHAR(100) NOT NULL COMMENT 'simulated_webhook, marked_as_failed, manual_intervention',
    
    -- Recovery timing
    recovered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When recovery action was taken',
    original_order_created_at TIMESTAMP COMMENT 'When original order was created',
    recovery_delay_minutes INT GENERATED ALWAYS AS (TIMESTAMPDIFF(MINUTE, original_order_created_at, recovered_at)) COMMENT 'Time between order creation and recovery',
    
    -- Recovery data
    recovery_data TEXT COMMENT 'JSON data about recovery action taken',
    revenuecat_customer_info TEXT COMMENT 'Customer info fetched from RevenueCat API',
    
    -- Success tracking  
    recovery_successful BOOLEAN DEFAULT TRUE COMMENT 'Whether recovery action succeeded',
    recovery_error_message TEXT COMMENT 'Error message if recovery failed',
    
    -- Audit fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes
    INDEX idx_recovery_logs_order_id (order_id),
    INDEX idx_recovery_logs_customer_id (customer_id),
    INDEX idx_recovery_logs_recovery_reason (recovery_reason),
    INDEX idx_recovery_logs_recovered_at (recovered_at),
    INDEX idx_recovery_logs_recovery_successful (recovery_successful),
    INDEX idx_recovery_logs_customer_recovered (customer_id, recovered_at)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Logs all webhook recovery actions taken by the recovery system';

-- 3. Webhook Monitoring Stats (Aggregated monitoring data)
CREATE TABLE webhook_monitoring_stats (
    id VARCHAR(255) PRIMARY KEY,
    date_hour TIMESTAMP NOT NULL COMMENT 'Hour being tracked (YYYY-MM-DD HH:00:00)',
    
    -- Processing counts
    total_webhooks_received INT DEFAULT 0 COMMENT 'Total webhooks received this hour',
    webhooks_processed_successfully INT DEFAULT 0 COMMENT 'Successfully processed webhooks',
    webhooks_failed INT DEFAULT 0 COMMENT 'Failed webhook processing attempts',
    duplicate_webhooks_blocked INT DEFAULT 0 COMMENT 'Duplicate webhooks prevented by idempotency',
    
    -- Event type breakdown
    initial_purchase_count INT DEFAULT 0,
    renewal_count INT DEFAULT 0,
    cancellation_count INT DEFAULT 0,
    expiration_count INT DEFAULT 0,
    
    -- Recovery stats
    recovery_events_processed INT DEFAULT 0 COMMENT 'Recovery webhooks processed',
    orders_recovered INT DEFAULT 0 COMMENT 'Orders recovered from failures',
    
    -- Performance stats
    avg_processing_time_ms DECIMAL(10,2) DEFAULT 0 COMMENT 'Average processing time in milliseconds',
    max_processing_time_ms INT DEFAULT 0 COMMENT 'Longest processing time this hour',
    
    -- Audit fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Unique constraint and indexes
    UNIQUE KEY unique_date_hour (date_hour),
    INDEX idx_monitoring_stats_date_hour (date_hour),
    INDEX idx_monitoring_stats_failure_rate (date_hour, webhooks_failed, total_webhooks_received)
    
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Hourly aggregated statistics for webhook processing monitoring';

-- Add foreign key constraints where applicable
-- Note: We don't add FK to orders table as recovery might happen before order exists

-- Create indexes for common queries
CREATE INDEX idx_webhook_logs_customer_status_date ON webhook_processing_logs (customer_id, status, started_at);
CREATE INDEX idx_recovery_logs_date_reason ON webhook_recovery_logs (recovered_at, recovery_reason);

-- Insert sample monitoring stats structure for current hour
INSERT IGNORE INTO webhook_monitoring_stats (id, date_hour) 
VALUES (
    CONCAT('stats_', DATE_FORMAT(NOW(), '%Y%m%d_%H')), 
    DATE_FORMAT(NOW(), '%Y-%m-%d %H:00:00')
);

-- Show created tables
SHOW TABLES LIKE '%webhook%';

-- Show table structures
DESCRIBE webhook_processing_logs;
DESCRIBE webhook_recovery_logs;
DESCRIBE webhook_monitoring_stats;